dbt_f1_transformations:
  target: dev
  outputs:
    dev:
      type: duckdb
      # Use a local DuckDB file; absolute Windows path.
      path: "F:/DaTech/Production/f1_data_project/f1_local_warehouse.duckdb"
      threads: 1
